//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineQuiz_bsef17m35
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string countryCode { get; set; }
        public string city { get; set; }
        public string type { get; set; }
        public string gender { get; set; }
        public string profilePicturePath { get; set; }
        public bool active { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual EndUserType EndUserType { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
