//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineQuiz_bsef17m35
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int quizId { get; set; }
        public int teacherId { get; set; }
        public int studentId { get; set; }
        public string content { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
