//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineQuiz_bsef17m35.student_quizzes
{


  public partial class open_quizzes
  {

    /// <summary>
    /// openQuizzesRepeater control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Repeater openQuizzesRepeater;

    /// <summary>
    /// selectedQuizEmail control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField selectedQuizEmail;

    /// <summary>
    /// selectedQuizId control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField selectedQuizId;

    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new onlineQuiz_bsef17m35.student_quizzes.student_quizzes Master
    {
      get
      {
        return ((onlineQuiz_bsef17m35.student_quizzes.student_quizzes)(base.Master));
      }
    }
  }
}
